name: Cache
description: Restore and Save directories using a cache key & tarballs
author: https://github.com/gencer
requirements:
  - aws
  - tar
configuration:
  properties:
    rsync_storage:
      type: string
    tarball_storage:
      type: string
    tarball_keep_max_days:
      type: number
    cache_key:
      type: string
    paths:
      type: [ string, array ]
    env:
      type: [ string, array ]
      minimum: 1
    skip_save:
      type: boolean
    skip_restore:
      type: boolean
    save:
      type: array
      minimum: 1
      items:
        type: object
        properties:
          key: string
          paths:
            type: [string, array]
            minimum: 1
          name: 
            type: string
          when: 
            type: string
            enum: [ "always", "on_success", "on_failure" ]
        required: [ "key", "paths" ]
    restore:
      type: array
      minimum: 1
      items:
        type: object
        properties:
          key: string
          name: 
            type: string
        required: [ "key" ]
  oneOf:
    - required:
      - save
    - required:
      - restore
  additionalProperties: false
